version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    networks:
      - nginx_network
    ports:
      - "80:80"
    volumes:
      - ./nginx_html:/usr/share/nginx/html
      - ./config:/etc/nginx/conf.d

networks:
  nginx_network: